In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("Data/TA_restaurants_curated.csv",encoding='utf8')

In [3]:
data

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4.0,5.0,$$$$,564.0,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5.0,4.5,$$$$,316.0,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170
...,...,...,...,...,...,...,...,...,...,...,...
125522,1662,Konrad Kaffee- & Cocktailbar,Zurich,NaN,NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13273526-Reviews-K...,d13273526
125523,1663,Blueberry American Bakery,Zurich,['Cafe'],NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13292844-Reviews-B...,d13292844
125524,1664,Restaurant Bahnhof,Zurich,NaN,NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13296092-Reviews-R...,d13296092
125525,1665,Yoyo Pizza,Zurich,['Fast Food'],NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13323362-Reviews-Y...,d13323362
125526,1666,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",NaN,NaN,$$ - $$$,NaN,NaN,/Restaurant_Review-g188113-d13349842-Reviews-D...,d13349842

In [64]:
# Observo bien los datos de los que se forma mi dataset.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125527 entries, 0 to 125526
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         125527 non-null  int64
 1   Name               125527 non-null  object
 2   City               125527 non-null  object
 3   Cuisine Style      94176 non-null   object
 4   Ranking            115876 non-null  float64
 5   Rating             115897 non-null  float64
 6   Price Range        77672 non-null   object
 7   Number of Reviews  108183 non-null  float64
 8   Reviews            115911 non-null  object
 9   URL_TA             125527 non-null  object
 10  ID_TA              125527 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 10.5+ MB

In [5]:
# Ver si hay alguna fila completamente formada por valores "NaN" y de ser asÃ­ eliminarlas.
data1 = data.dropna(how = "all")

In [6]:
data1

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1.0,5.0,$$ - $$$,136.0,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2.0,4.5,$$$$,812.0,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3.0,4.5,$$$$,567.0,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4.0,5.0,$$$$,564.0,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5.0,4.5,$$$$,316.0,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170
...,...,...,...,...,...,...,...,...,...,...,...
125522,1662,Konrad Kaffee- & Cocktailbar,Zurich,NaN,NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13273526-Reviews-K...,d13273526
125523,1663,Blueberry American Bakery,Zurich,['Cafe'],NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13292844-Reviews-B...,d13292844
125524,1664,Restaurant Bahnhof,Zurich,NaN,NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13296092-Reviews-R...,d13296092
125525,1665,Yoyo Pizza,Zurich,['Fast Food'],NaN,NaN,NaN,NaN,NaN,/Restaurant_Review-g188113-d13323362-Reviews-Y...,d13323362
125526,1666,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",NaN,NaN,$$ - $$$,NaN,NaN,/Restaurant_Review-g188113-d13349842-Reviews-D...,d13349842

In [17]:
# Cambiar "NaN" por guiones.
data2 = data1.fillna('-')

In [18]:
data2

,Unnamed: 0,Name,City,Cuisine Style,Ranking,Rating,Price Range,Number of Reviews,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1,5,$$ - $$$,136,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2,4.5,$$$$,812,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3,4.5,$$$$,567,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4,5,$$$$,564,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5,4.5,$$$$,316,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170
...,...,...,...,...,...,...,...,...,...,...,...
125522,1662,Konrad Kaffee- & Cocktailbar,Zurich,-,-,-,-,-,-,/Restaurant_Review-g188113-d13273526-Reviews-K...,d13273526
125523,1663,Blueberry American Bakery,Zurich,['Cafe'],-,-,-,-,-,/Restaurant_Review-g188113-d13292844-Reviews-B...,d13292844
125524,1664,Restaurant Bahnhof,Zurich,-,-,-,-,-,-,/Restaurant_Review-g188113-d13296092-Reviews-R...,d13296092
125525,1665,Yoyo Pizza,Zurich,['Fast Food'],-,-,-,-,-,/Restaurant_Review-g188113-d13323362-Reviews-Y...,d13323362
125526,1666,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",-,-,$$ - $$$,-,-,/Restaurant_Review-g188113-d13349842-Reviews-D...,d13349842

In [65]:
# Observo que hay columnas que tienen el nombre formado por varias palabras y esto es un problema para luego trabajar con ellas.
# Por tanto, cambio los nombres de esas columnas para solventar este inconveniente.
data2.rename(columns={'Cuisine Style':'Cuisine_style','Price Range':'Price_range','Number of Reviews':'Reviews_number'}, inplace=True)

In [43]:
data2

,Unnamed: 0,Name,City,Cuisine_style,Ranking,Rating,Price_range,Reviews_number,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1,5,$$ - $$$,136,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2,4.5,$$$$,812,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3,4.5,$$$$,567,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4,5,$$$$,564,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5,4.5,$$$$,316,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170
...,...,...,...,...,...,...,...,...,...,...,...
125522,1662,Konrad Kaffee- & Cocktailbar,Zurich,-,-,-,-,-,-,/Restaurant_Review-g188113-d13273526-Reviews-K...,d13273526
125523,1663,Blueberry American Bakery,Zurich,['Cafe'],-,-,-,-,-,/Restaurant_Review-g188113-d13292844-Reviews-B...,d13292844
125524,1664,Restaurant Bahnhof,Zurich,-,-,-,-,-,-,/Restaurant_Review-g188113-d13296092-Reviews-R...,d13296092
125525,1665,Yoyo Pizza,Zurich,['Fast Food'],-,-,-,-,-,/Restaurant_Review-g188113-d13323362-Reviews-Y...,d13323362
125526,1666,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",-,-,$$ - $$$,-,-,/Restaurant_Review-g188113-d13349842-Reviews-D...,d13349842

In [22]:
print(data2['Price_range'].value_counts())

$$ - $$$    54360
-           47855
$           19005
$$$$         4307
Name: Price_range, dtype: int64

In [58]:
# Cambiar los tipos de precio que aparecen. Quitar los sÃ­mbolos de dolares y cambiarlo por algo mas sencillo de entender.
data3 = data2.replace({"$": "cheap", "$$ - $$$": "medium", "$$$$": "high", "-": "not-inf"})

In [59]:
data3

,Unnamed: 0,Name,City,Cuisine_style,Ranking,Rating,Price_range,Reviews_number,Reviews,URL_TA,ID_TA
0,0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1,5,medium,136,"[['Just like home', 'A Warm Welcome to Wintry ...",/Restaurant_Review-g188590-d11752080-Reviews-M...,d11752080
1,1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2,4.5,high,812,"[['Great food and staff', 'just perfect'], ['0...",/Restaurant_Review-g188590-d693419-Reviews-De_...,d693419
2,2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3,4.5,high,567,"[['Satisfaction', 'Delicious old school restau...",/Restaurant_Review-g188590-d696959-Reviews-La_...,d696959
3,3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4,5,high,564,"[['True five star dinner', 'A superb evening o...",/Restaurant_Review-g188590-d1239229-Reviews-Vi...,d1239229
4,4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5,4.5,high,316,"[['Best meal.... EVER', 'super food experience...",/Restaurant_Review-g188590-d6864170-Reviews-Li...,d6864170
...,...,...,...,...,...,...,...,...,...,...,...
125522,1662,Konrad Kaffee- & Cocktailbar,Zurich,not-inf,not-inf,not-inf,not-inf,not-inf,not-inf,/Restaurant_Review-g188113-d13273526-Reviews-K...,d13273526
125523,1663,Blueberry American Bakery,Zurich,['Cafe'],not-inf,not-inf,not-inf,not-inf,not-inf,/Restaurant_Review-g188113-d13292844-Reviews-B...,d13292844
125524,1664,Restaurant Bahnhof,Zurich,not-inf,not-inf,not-inf,not-inf,not-inf,not-inf,/Restaurant_Review-g188113-d13296092-Reviews-R...,d13296092
125525,1665,Yoyo Pizza,Zurich,['Fast Food'],not-inf,not-inf,not-inf,not-inf,not-inf,/Restaurant_Review-g188113-d13323362-Reviews-Y...,d13323362
125526,1666,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",not-inf,not-inf,medium,not-inf,not-inf,/Restaurant_Review-g188113-d13349842-Reviews-D...,d13349842

In [60]:
# Verificar que el cambio se ha realizado correctamente.
print(data3['Price_range'].value_counts())

medium     54360
not-inf    47855
cheap      19005
high        4307
Name: Price_range, dtype: int64

In [61]:
# Decido quitar las columnas que no me sirven para mi posterior anÃ¡lisis.
restaurant_europe_data = data3.drop(['Unnamed: 0', 'URL_TA', 'ID_TA'], axis=1)

In [62]:
restaurant_europe_data

,Name,City,Cuisine_style,Ranking,Rating,Price_range,Reviews_number,Reviews
0,Martine of Martine's Table,Amsterdam,"['French', 'Dutch', 'European']",1,5,medium,136,"[['Just like home', 'A Warm Welcome to Wintry ..."
1,De Silveren Spiegel,Amsterdam,"['Dutch', 'European', 'Vegetarian Friendly', '...",2,4.5,high,812,"[['Great food and staff', 'just perfect'], ['0..."
2,La Rive,Amsterdam,"['Mediterranean', 'French', 'International', '...",3,4.5,high,567,"[['Satisfaction', 'Delicious old school restau..."
3,Vinkeles,Amsterdam,"['French', 'European', 'International', 'Conte...",4,5,high,564,"[['True five star dinner', 'A superb evening o..."
4,Librije's Zusje Amsterdam,Amsterdam,"['Dutch', 'European', 'International', 'Vegeta...",5,4.5,high,316,"[['Best meal.... EVER', 'super food experience..."
...,...,...,...,...,...,...,...,...
125522,Konrad Kaffee- & Cocktailbar,Zurich,not-inf,not-inf,not-inf,not-inf,not-inf,not-inf
125523,Blueberry American Bakery,Zurich,['Cafe'],not-inf,not-inf,not-inf,not-inf,not-inf
125524,Restaurant Bahnhof,Zurich,not-inf,not-inf,not-inf,not-inf,not-inf,not-inf
125525,Yoyo Pizza,Zurich,['Fast Food'],not-inf,not-inf,not-inf,not-inf,not-inf
125526,dieci,Zurich,"['Italian', 'Pizza', 'Mediterranean', 'Diner']",not-inf,not-inf,medium,not-inf,not-inf

In [63]:
restaurant_europe_data.to_csv('restaurant_europe_data.csv')